---
- name: Verify that required parameters are set
  ansible.builtin.assert:
    that:
      - '{{ item }} is defined'
      - '{{ item }} | length > 0'
  with_items:
    - cloudinit_rendering
    - alias
    - profiles
    - host

# - name: Verify that required parameters are set - bool
#   assert:
#     that:
#       - postgres.auto_create_accounts is defined
#       - postgres.auto_create_accounts | bool
...
