---
- name: Check if role exist
  ansible.builtin.stat:
    path: roles/ansible_role_cloud_init
  delegate_to: localhost
  register: path_ansible_role_cloud_init

- name: No role ansible_role_cloud_init  # noqa ignore-errors
  ansible.builtin.fail:
    msg: "roles/ansible_role_cloud_init not found so don't run that role"
  failed_when: not path_ansible_role_cloud_init.stat.exists
  ignore_errors: true

- name: Include role - ansible_role_cloud_init
  ansible.builtin.include_role:
    name: ansible_role_cloud_init
  when: path_ansible_role_cloud_init.stat.exists
...
